export const SET_USER = 'SET_USER';
export const DELETE_USER = 'DELETE_USER';

export const SET_SESSION_ID = 'SET_SESSION_ID';
export const DELETE_SESSION_ID = 'DELETE_SESSION_ID';

export const IS_SHOW_LOGIN_MODAL = 'IS_SHOW_LOGIN_MODAL';
export const UPDATE_IS_AUTH = 'UPDATE_IS_AUTH';

export const UPDATE_PAGE = 'UPDATE_PAGE';
export const UPDATE_TOTAL_PAGE = 'UPDATE_TOTAL_PAGE';

export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const ADDED_GENRES = 'ADDED_GENRES';
export const DELETE_GENRES = 'DELETE_GENRES';
export const UPDATE_MOVIES = 'UPDATE_MOVIES';